<?php

return [
    'mainPageTitle' => 'Crypto application - Main page',
    'metaComment' => 'Home page of the educational web application. This application focuses on teaching cryptography and is a thesis project on TLS Security.',
    'cryptoInNutshell' => 'Cryptology in a nutshell',
    'annotation' => 'One of the most important parts of keeping information confidential is cryptography. In the encryption process, we convert the original "open" readable message into ciphertext. Depending on the algorithm used, the resulting text should be meaningless or directly unreadable to a subject who does not know the auxiliary information to decrypt it. This process is carried out according to predefined rules or by means of a chosen algorithm. An example of the resulting encryption product may be a random mixture of numbers, letters, words or nonsense sentences. <br/><br/> This subcategory of cryptology deals with the overall view of data encryption, also under this category we include reverse decryption. It also examines the security of the encryption algorithms used or the overall security of encryption systems. An essential part of this is the design of encryption and decryption keys used in encryption algorithms and their possible internal calculations.',
    'symetric' => 'Symmetric algorithms',
    'symetricInfo' => 'When using a symmetric algorithm, a key is used that is identical for encryption and decryption. This variant is simple, but if the key is broken in one transmitted ciphertext, the rest of the ciphertext where the key is used will be broken.
    <br /> <br/> Typical uses of this type of key are found in block ciphers, as well as substitution and transposition ciphers. This block cipher uses an implementation of the Feistel function. Uses can be found, for example, in the DES (Data Encryption Standard) algorithm.
    <br /> <br/> The advantage of DES is the possibility of using the "avalanche" effect, where a large change in the ciphertext occurs when editing an open text. The use of DES is not very secure, it is better to use its replacement called AES. Symmetric algorithms are more suitable for archiving confidential information without sending it to the other entity.',
    'asymetric' => 'Asymmetric algorithms',
    'asymetricInfo' => 'The term asymmetric algorithm hides the use of two different keys. Both keys have their specific task and cannot be used for anything else. We use a key for encryption (public) and also a different key for decryption (private).
    <br/> <br/>To communicate with the recipient, it is then necessary to pass the private key in a closed line to prevent leakage of the information. Modern algorithms can now take care of this issue themselves. A prime example is the RSA algorithm and digital signature security.
    <br/> <br/>In order to achieve asymmetric encryption, three basic requirements need to be met. The first condition is the aforementioned use of two different keys. The second condition is to ensure that the original text cannot be extracted from the ciphertext even with knowledge of the public key. The third and last necessary condition is the "uncomputability" of the private key. This property is achieved by using a one-sided function.',
    'usage' => 'Usage of cryptography',
    'usageInfo' => 'Advanced encryption is currently used virtually everywhere where personal or secret information needs to be kept secret. A prime example is passwords stored in databases. <br/> <br/> Another example is network protocols such as TLS and SSL, which ensure that communication between client and server is secure. This part is mainly visible in web browsers due to the well-known HTTPS and the iconic padlock next to the address text box. The use of cryptography is also important in the area of mobile payments or the creation of digital signatures.',
    'protocols' => 'Protocols',
    'protocolsInfo' => 'In order to explain cryptographic protocols, it is necessary to define the word "protocol" and understand its meaning. A protocol is a set of rules and instructions specifying how a given system should behave and react in a certain situation. Protocols are used virtually everywhere in information technology.<br/> <br/>
A cryptographic protocol is one that provides secure communication between devices on a network. Its tasks are, for example, to ensure agreement on private and public keys, to provide a secure connection, to encrypt communication with a symmetric algorithm. It is composed of smaller units of so-called "cryptographic primitives" that are always aimed at doing one specific thing. <br/> <br/>
Cryptographic primitives are cryptographic algorithms specifically designed for the purpose of building a cryptographic protocol, and their focus on a single task makes them highly reliable. If a vulnerability occurs in these primitives, all protocols that use the primitives are at risk. <br/> <br/>
The most well-known and most used cryptographic protocols by users are SSL, TLS, SSH.',
    'sslvstlsInfo' => 'In the field of cryptography, the best known cryptographic protocols are Secure Socket Layer (SSL) and Transport Layer Security (TLS). They were created to ensure secure and encrypted communication on the network. These protocols focus on authentication of both devices and subsequent encrypted transmissions at the application layer . <br/> <br/> Currently, SSL is labeled as "obsolete" and is being replaced by a newer version called TLS, which has patched vulnerabilities from the original SSL. If a client wants to encrypt their traffic in this way they need to specify this to the server. The easiest way to achieve this communication is then by using the specified port. An example is https on port 443. <br/><br/> Communication is done in several steps. The first step is the "handshake", which is the step where the client requests a secure connection from the server and agrees on the parameters for the session, specifically the encryption keys and the use of the encryption algorithm. This process uses asymmetric encryption, but further communication is done using symmetric algorithms. <br/><br/> In the first step, the server also sends its SSL/TLS certificate to the client, which then verifies it. After verification and successful completion of the handshake phase, the secure connection is initiated.',
    'certificates' => 'SSL/TLS Certificates',
    'certificatesInfo' => 'SSL/TLS certificates are a way to verify the security of a connection to a server. These certificates allow encryption of HTTP traffic, which is manifested by the familiar HTTPS prefix and lock icon in web browsers. The generated certificate contains the domain name, organization name, certificate issuer name, date of issuance, expiration date, digital signature, and public key. It may also contain any subdomains . <br/><br/> When connecting to a server under an encrypted port, this certificate is sent to the client in the "handshake" phase. The client verifies the received certificate on the issuer side before further communication. This check ensures that the server is who it claims to be. If the certificate is valid and its verification at the issuer side is also valid, then it proceeds to the next communication otherwise the handshake and connection is terminated.',


];
