<?php

return [
    'mainPageTitle' => 'EduCrypter - Main page',
    'metaComment' => 'Home page of the educational web application. This application focuses on teaching cryptography and is a thesis project on TLS Security.',
    'cryptoInNutshell' => 'Cryptography in a nutshell',
    'annotation' => 'One of the most important parts of keeping information confidential is cryptography. In the encryption process, we convert the original "open" readable message into ciphertext. Depending on the algorithm used, the resulting text should be meaningless or directly unreadable for an entity that does not know the auxiliary information for decryption. This process is carried out according to predetermined rules or by means of a chosen algorithm. An example of the final product of encryption may be a random mixture of numbers, letters, words. <br /><br /> This subcategory of cryptology deals with the overall view of data encryption. It also examines the security of the used encryption algorithms or, possibly, the overall security of encryption systems. An essential part is also the creation and management of encryption and decryption keys, which are used in encryption algorithms and their possible internal calculations. Cryptanalysis deals with deciphering and breaking ciphers.',
    'symmetric' => 'Symmetric algorithms',
    'symmetricInfo' => 'When using a symmetric algorithm, a key is used that is identical for both encryption and decryption. This variant is simple, but breaking the key in one transmitted ciphertext will break the rest where the key is used. <br /> <br/> The typical use of this type of key can be found in block ciphers, as well as substitution and transposition ciphers. For example, an implementation of the Feistel function is used for block encryption in the DES (Data Encryption Standard) algorithm. <br /> <br/> The advantage of DES is the possibility of using the "avalanche" effect, when editing the plain text causes a big change in the encrypted text. Using DES is not very secure, it is better to use its successor called AES.
                        Symmetric encryption algorithms are widely used in cybersecurity and cryptography due to their speed, efficiency, and reliability. They are suitable for securing communication over the Internet, data storage, mobile devices, IoT, file encryption, authentication and data integrity, VPN and embedded systems. However, it is important to ensure proper key management and implement security procedures to minimize risks.',
    'asymmetric' => 'Asymmetric algorithms',
    'asymmetricInfo' => 'The term asymmetric algorithm hides the use of two different keys. Both keys have their specific task. We use a key for encryption (public) and also a different key for decryption (private). <br /> <br/> In order to communicate with the recipient, it is then necessary to transfer the private key in the secure channel in order to prevent leakage of the given information. Modern cryptosystems can usually solve this problem by themselves. <br/> <br/> To achieve asymmetric encryption, three basic required conditions must be met. The first condition is the aforementioned use of two different keys. The second condition is to ensure that the original text cannot be obtained from the encrypted text even with knowledge of the public key. The third and last necessary condition is the "incomputability" of the private key. This property is achieved by using a one-way function.',
    'usage' => 'Usage of cryptography',
    'usageInfo' => 'Advanced encryption is currently used virtually everywhere where personal or secret information needs to be kept secret. A prime example is passwords stored in databases. <br/> <br/> Another example is network protocols such as TLS and SSL, which ensure that communication between client and server is secure. This part is mainly visible in web browsers due to the well-known HTTPS and the iconic padlock next to the address text box. The use of cryptography is also important in the area of mobile payments or the creation of digital signatures.',
    'protocols' => 'Protocols',
    'protocolsInfo' => 'In order to explain cryptographic protocols, it is necessary to define the word \'protocol\' and understand its meaning. A protocol is a set of rules and instructions specifying how a given system should behave and react in a certain situation. Protocols are used virtually everywhere in information technology.<br/> <br/>
A cryptographic protocol is one that provides secure communication between devices on a network. Its tasks are, for example, to ensure agreement on private and public keys, to provide a secure connection, to encrypt communication with a symmetric algorithm. It is composed of smaller units of so-called \'cryptographic primitives\' that are always aimed at doing one specific thing. <br/> <br/>
Cryptographic primitives are cryptographic algorithms specifically designed for the purpose of building a cryptographic protocol, and their focus on a single task makes them highly reliable. If a vulnerability occurs in these primitives, all protocols that use the primitives are at risk. <br/> <br/>
The most well-known and most used cryptographic protocols by users are SSL and TLS.',
    'sslvstlsInfo' => 'In the field of cryptology, the most well-known cryptographic protocols are Secure Socket Layer (SSL) and Transport Layer Security (TLS). They were created with the aim of ensuring secure and encrypted communication on the network. The mentioned protocols focus on the verification of both devices and subsequent encrypted transmissions in the area of the application layer. <br/> <br/> SSL is currently marked as "deprecated" and is being replaced by the newer TLS. This technology has a large number of vulnerabilities fixed in the latest version compared to the original SSL. If the client wants to encrypt its traffic in this way, it must be specified to the server. The easiest way to achieve this communication is to use the specified port. An example is https on port 443. <br/><br/> Communication takes place in several steps. The first step is the "handshake", which is a step in which the client asks the server for a secure connection and agrees on the parameters for the given session, specifically the encryption keys and the use of the encryption algorithm. This process uses asymmetric encryption, but other communication takes place using symmetric algorithms. <br/><br/> In the first step, the server also sends its SSL/TLS certificate to the client, which then verifies it. After authentication and successful completion of the "handshake" phase, a secure connection is initiated.',
    'certificates' => 'SSL/TLS Certificates',
    'certificatesInfo' => 'SL/TLS certificates are an option to verify the security of the connection to the server. These certificates enable the encryption of HTTP traffic, which is manifested by the well-known HTTPS prefix and the lock icon in Internet browsers. The generated certificate contains, for example, domain name, organization name, certificate issuer name, issue date, expiration date, digital signature, public key, and other important information. It can also contain any subdomains. <br/><br/> When connecting to the server under an encrypted port, this certificate is sent to the client in the "handshake" phase. The client verifies the received certificate on the issuers side before further communication. This check ensures that the server is who it says it is. If the certificate is valid and its verification on the issuers side as well, then the next communication is moved on, otherwise the handshake and the connection are terminated.',
    'infoBannerTitle' => 'Application testing notice',
    'infoBanner' => 'After trying the <b>EduCrypter</b> web application, I ask you to fill out the questionnaire using the <a href="https://forms.gle/s4WVh4rjetFtG7Cu6">form</a>. This questionnaire is completely anonymous and the data obtained is used to evaluate the feedback for the master thesis. <br /> Thank you in advance for filling it out.'
];
