version: '3.4'

services:
  php:
    container_name: 'php'
    build:
      context: ./docker/php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
