version: '3.8'

services:
  educrypter-php:
    build:
      context: ./docker/php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
