version: '3.4'

services:
  php:
    container_name: 'php'
    build:
      context: ./docker/php
    ports:
      - "80:80"
    environment:
      ENVIRONMENT: "production"
    volumes:
      - .:/var/www/html
      - .:/etc/ssl/certs
      - .:/etc/ssl/private
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    restart: always
