version: '3.4'

services:
  php:
    container_name: 'php'
    build:
      context: ./docker/php
    ports:
      - "80:80"
    environment:
      ENVIRONMENT: "production"
    volumes:
      - .:/var/www/html
      # This volume is for production - place key and cert in it
      - ./ssl:/etc/apache2/ssl
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    restart: always
