version: '3.4'

services:
  php:
    container_name: 'php'
    build:
      context: ./docker/php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - "$PWD/docker/log:/var/log/apache2"
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    restart: always
