version: '3.4'

services:
  educrypter-php:
    build:
      context: ./docker/php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/CryptographyApp
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
