<?php

return [
    'metaComment' => 'Úvodní stránka výukové webové aplikace. Tato aplikace se zaměřuje na výuku kryptografie a je projektem diplomové práce na téma Zabezpečení TLS.',
    'cryptoInNutshell' => 'Kryptologie v kostce',
    'annotation' => 'Jednou z nejdůležitějších částí při utajování informací ve zprávě je kryptografie. Při procesu šifrování převádíme původní „otevřenou“ čitelnou zprávu na zašifrovaný text. Výsledný text by v závislosti na použitém algoritmu měl být nesmyslný či přímo nečitelný pro entitu, která nezná pomocné informace k dešifrování. Tento proces se provádí dle předem určených pravidel či pomocí zvoleného algoritmu. Příkladem finálního produktu šifrování může být náhodná směsice čísel, písmen, slov, nesmyslných vět. <br /><br /> Tato podkategorie kryptologie se zabývá celkovým pohledem na šifrování dat, taktéž pod tuto kategorii spadá zpětná dešifrace. Dále zkoumá bezpečnost použitých šifrovacích algoritmů či případně celkovou bezpečnost šifrovacích systémů. Podstatnou částí je i tvorba šifrovacích a dešifrovacích klíčů, které se využívají v šifrovacích algoritmech a jejich případných interních výpočtech.',
    'symetric' => 'Symetrické algoritmy',
    'symetricInfo' => 'Při použití symetrického algoritmu se využije klíč, který je totožný pro šifrování i dešifrování. Tato varianta je jednoduchá, avšak při prolomení klíče v jednom přeneseném zašifrovaném textu dojde k prolomení zbytku, kde je klíč použit. <br /> <br/> Typické využití tohoto typu klíče lze nalézt u blokových šifer, dále se jedná o substituční a transpoziční šifry. Toto šifrování pomocí bloků využívá implementace Feistelovy funkce. Využití lze nalézt například v algoritmu DES (Data Encryption Standard). <br /> <br/> Výhodou DES je možnost využití „lavinového“ efektu, kdy při editaci otevřeného textu nastane velká změna v šifrovaném textu. Použití DES není příliš bezpečné, lepší je využít jeho náhradníka s názvem AES. Symetrické algoritmy jsou spíše vhodné pro archivaci důvěrných informací bez posílání druhé entitě.',
    'asymetric' => 'Asymetrické algoritmy',
    'asymetricInfo' => 'Pod pojmem asymetrický algoritmus se schovává využití dvou odlišných klíčů. Oba klíče mají svůj specifický úkol a na nic jiného je nelze využít. Využíváme klíč na šifrování (veřejný) a také odlišný klíč určený k dešifrování (privátní). <br /> <br/> Pro komunikaci s příjemcem je pak nutné předat privátní klíč v uzavřené lince, aby nedošlo k úniku daných informací. O tuto záležitost se nyní dokážou postarat moderní algoritmy samy. Ukázkovým příkladem je algoritmus RSA a zabezpečení digitálním podpisem. <br/> <br/> K dosažení asymetrického šifrování je zapotřebí splnit tři základní požadované podmínky. První podmínkou je již zmíněné využití dvou různých klíčů. Druhou podmínkou je zajistit, aby ze zašifrovaného textu nebylo možné získat původní text i se znalostí veřejného klíče. Třetí a poslední nutnou podmínkou je „nevypočitatelnost“ privátního klíče. Této vlastnosti se dosahuje pomocí využití jednostranné funkce.',
    'usage' => 'Využití kryptografie',
    'usageInfo' => 'Pokročilé šifrování se v současné době využívá prakticky všude, kde je potřeba utajit osobní či tajné informace. Ukázkovým příkladem mohou být hesla uložená v databázích. <br/> <br/> Dalším příkladem jsou síťové protokoly typu TLS a SSL, které zajišťují, aby komunikace mezi klientem a serverem probíhala bezpečně. Tato část je především viditelná ve webových prohlížečích díky známému HTTPS a ikonickému zámečku vedle textového pole s adresou. Využití kryptografie je významné také v oblasti mobilních plateb či tvorbě digitálních podpisů.',
    'protocols' => 'Protokoly',
    'protocolsInfo' => 'Pro vysvětlení kryptografických protokolů je potřeba definovat si slovo „protokol“ a pochopit jeho význam. Protokol je sada pravidel a instrukcí určující, jak se má daný systém zachovat v určité situaci a reagovat na ni. Protokoly se používají prakticky všude v oblasti informačních technologií. <br/> <br/> Kryptografický protokol je takový protokol, který zajišťuje bezpečnou komunikaci mezi zařízeními na síti. Jeho úkoly jsou například zajištění dohody na privátních a veřejných klíčích, zajištění bezpečného spojení, šifrování komunikace symetrickým algoritmem. Je složen z menších celků takzvaných „kryptografických primitiv“, které jsou vždy zaměřeny na provádění jedné specifické věci. <br/><br/> Kryptografické primitiva jsou šifrovací algoritmy speciálně vytvořené za účelem stavby kryptografického protokolu a díky jejich zaměření na jeden úkol jsou vysoce spolehlivé. Pokud se u těchto prvků vyskytne zranitelnost, jsou ohroženy všechny protokoly, které daných primitiv využívají. <br/><br/> Mezi nejznámější a nejvíce uživateli používané kryptografické protokoly patří SSL, TLS, SSH.',
    'sslvstlsInfo' => 'V oblasti kryptologie jsou nejznámější především kryptografické protokoly Secure Socket Layer (SSL) a Transport Layer Security (TLS). Vytvořeny byli s cílem zajistit bezpečnou a šifrovanou komunikaci na síti. Zmíněné protokoly se zaměřují na ověření obou zařízení a následné šifrované přenosy v oblasti aplikační vrstvy. <br/> <br/> V současné době je SSL označeno jako „zastaralé“ a je nahrazováno novější verzí s názvem TLS, které má opravené zranitelnosti z původního SSL. Pokud klient chce svůj provoz šifrovat tímto způsobem je nutno to serveru specifikovat. Nejjednodušší způsob, jak dosáhnout této komunikace je pak užitím specifikovaného portu. Příkladem je https na portu 443. <br/><br/> Komunikace probíhá v několika krocích. Prvním krokem je „handshake“, což je krok, ve kterém klient požádá server o zabezpečené spojení a domlouvá se na parametrech pro danou session, specificky pak šifrovací klíče a použití šifrovacího algoritmu. Tento proces využívá asymetrického šifrování, další komunikace však probíhá pomocí symetrických algoritmů. <br/><br/> V prvním kroku taktéž server odesílá svůj SSL/TLS certifikát ke klientovi, který ho následně ověřuje. Po ověření a úspěšném dokončení fáze „handshake“ se zahajuje zabezpečené spojení.',
    'certificates' => 'Certifikáty SSL/TLS',
    'certificatesInfo' => 'SSL/TLS certifikáty jsou možností, jak ověřit bezpečnost připojení k serveru. Tyto certifikáty umožňují šifrování HTTP přenosu, což se projevuje známým prefixem HTTPS a ikonou zámečku v internetových prohlížečích. Vygenerovaný certifikát obsahuje název domény, název organizace, název vystavitele certifikátu, datum vystavení, datum zániku, digitální podpis a veřejný klíč. Taktéž může obsahovat případné subdomény. <br/><br/> Při připojení k serveru pod šifrovaným portem je tento certifikát odeslán klientovi ve fázi „handshake“. Klient přijatý certifikát ověřuje na straně vydavatele před další komunikací. Tato kontrola zajistí, že je server tím, za koho se vydává. Pokud je certifikát platný a jeho ověření na straně vydavatele také, pak se přechází k další komunikaci v opačném případě k ukončení handshaku a spojení.',
    ];
